
version: '1.0'

services:
  ngrok:
    image: wernight/ngrok
    ports:
    - "8081:8081"
    command:
    - /bin/sh
    - -c
    - |
      ngrok start --all
    volumes:
    - .:/home/ngrok/.ngrok2/
    depends_on:
    - api-service
    - nginx
    - mongo
  
  api-service:
    build: .
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/cnm9/HoangTrongBinh/ATTT_Project/modelDir:/home/node/app/modelDir
      - /home/cnm9/HoangTrongBinh/ATTT_Project/datasetDir:/home/node/app/datasetDir
      - /home/cnm9/HoangTrongBinh/ATTT_Project/sampleDir:/home/node/app/sampleDir
    ports:
      - 6789:6789

  mongo:
    image: mongo
    volumes: 
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      
  nginx:
    image: nginx
    ports:
    - "8080:8080"
    volumes:
    - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
